version: "3.5"
services:
    database:
        build: .
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: abc123456
            MYSQL_DATABASE: cursogoweb
            MYSQL_USER: admin
            MYSQL_PASSWORD: abc123456
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - overlay
volumes:
    db-volume:
networks:
    overlay:

